version: '3.9'

services:
  web:
    build: .
    container_name: flask_api
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - backend
    expose:
      - 5000
  
  db:
    image: postgres:15
    container_name: postgres_db
    ports:
      - "5437:5432"
    restart: always
    environment:
      POSTGRES_USER: userg3
      POSTGRES_PASSWORD: datag3
      POSTGRES_DB: mlg3
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend: